### ISSUE TITLE
Excessive spaces when using "Copy monosyllabic" button 

### ISSUE THREAD

**Issue by triphora** [paralogical/glish#17]
```"The quick brown fox jumps over the lazy dog" is an English language sentence that contains all the letters of the alphabet. The phrase is commonly used for touch typing practice, testing typewriters and computer keyboards, displaying examples of fonts, and other applications involving text where the use of all letters in the alphabet is desired.```

... becomes ...

```"The   quick   brown   fox   jumps   vohdh   the   bleelz   dog"   is   an   glish   gwuj   stes   that   ruktntz   all   the   legtz   of   the   feft.   The   phrase   is   ahmk   used   for   touch geyept   strahrs,   tengst   preyept   and   turkst   krawrjdz,   spahrngspst   plizmdz   of   fonts,   and   udhd   klarnz   vlahrng   text   where   the   use   of   all   legtz   in   the   feft   is   deyerdzdzd.   ```

Firefox 120.0.1 on Linux.

**Comment by paralogical** [comment]
I think this has been fixed!
