### ISSUE TITLE
Show output as IPA?

### ISSUE THREAD

**Issue by quantenzitrone** [paralogical/glish#23]
I struggle with the pronunciation of Glish especially with long words like `pawrpstst` or `stweyedhd` but also with words that have an ambiguous pronunciation for my written-english-to-sounds-translator in my head like `zawng` or `veevd`.

While it probably wouldn't make me able to pronounce `pawrpstst`, it would massively help if I had a way to see the pronunciation in an unambiguous alphabet like IPA.

Furthermore, from the video:
> Frankly, I think this [IPA] is what the alphabet really should be.

**Comment by paralogical** [comment]
totally! It would be great to have a toggle to choose IPA or respelled english
